#encoding: utf-8
host: localhost
development:
  adapter: postgresql
  encoding: utf8
  database: pokeagenda_development
  pool: 5

test:
  adapter: postgresql
  encoding: SQL_ASCII
  database: pokeagenda_test
  pool: 5
